### ISSUE TITLE
Add example for Python function

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aws-custom-runtime#5]

**Comment by tzununbekov** [comment]
Since python function example requires its own buldtemplate, bootstrap, etc, I put everything into dedicated repository - https://github.com/triggermesh/aws-python-runtime

**Comment by sebgoa** [comment]
Checking now. Might be good to keep everything in a single repo...(not sure..)

**Comment by tzununbekov** [comment]
I think it would be more correct to call this repository something like "aws-lambda-api" because it actually doesn't contain any runtimes but provides execution environment for Lambda custom runtimes
Another point is licensing - here we can put our license, but I'm not sure about [lambda](https://github.com/triggermesh/aws-lambda-runtime) runtimes. Need to discuss this question.

**Comment by sebgoa** [comment]
I am going to close this and we can take this discussion to the other repo
